changes for shallow copy
IBM/ibm-spectrum-scale-csi pull request #1067
Opened 2023-12-04 06:11 UTC by hemalathagajendran

## Pull request checklist

```release-notes

```

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature Enhancement
- [ ] Test Automation 
- [ ] Code Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Community Operator listing 
- [ ] Other (please describe): 

## What is the current behavior?

-

## What is the new behavior?

-

## How risky is this change?
- [ ] Small, isolated change
- [x] Medium, requires regression testing
- [ ] Large, requires functional and regression testing

2023-12-15 14:03 UTC, amdabhad submitted a review, later dismissed

2023-12-17 11:10 UTC, hemalathagajendran commented
Design doc: https://ibm.ent.box.com/file/1385848485070

Image: quay.io/hemalatha_gajendran/driver_shallowcopy_feature_latest:latest

2023-12-22 06:14 UTC, badri-pathak approved these changes, later dismissed

2023-12-22 09:10 UTC, Jainbrt requested changes

2023-12-22 09:10 UTC, Jainbrt commented on driver/csiplugin/controllerserver.go
> +	if isPvcFromSnap{
Should this be one of the if else condition in above code block ?

2023-12-22 09:10 UTC, Jainbrt commented on driver/csiplugin/controllerserver.go
> +		if reqCap.GetAccessMode().GetMode() == csi.VolumeCapability_AccessMode_MULTI_NODE_READER_ONLY {
should this code be replaced with older code ( line 648-650)?

2023-12-22 09:10 UTC, Jainbrt commented on driver/csiplugin/controllerserver.go
> +			return nil, status.Error(codes.Internal, "CreateVolume ValidateShallowCopyVolume failed")
it would a good idea, if we also print a error log message here with volume details.?

2024-01-09 05:06 UTC, saurabhwani5 approved these changes

2024-01-09 08:29 UTC, Jainbrt approved these changes

2024-01-09 09:14 UTC, merged