Fix for race condition during shallow copy deletion
IBM/ibm-spectrum-scale-csi pull request #1112
Opened 2024-03-11 08:38 UTC by hemalathagajendran

## Pull request checklist

Please check the type of change your PR introduces:
- [ x] Bugfix
- [ ] Feature Enhancement
- [ ] Test Automation 
- [ ] Code Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Community Operator listing 
- [ ] Other (please describe): 

## What is the current behavior?

- Race condition happens when shallow copy deletion and snapshot deletion happens in parallel

## What is the new behavior?

- Race condition doesn't happen when shallow copy deletion and snapshot deletion happens in parallel. Also when snapshot directory is deleted manually then also shallow copy deletion would get successful which was not happening previously.

## How risky is this change?
- [ ] Small, isolated change
- [ x] Medium, requires regression testing
- [ ] Large, requires functional and regression testing

2024-03-11 08:39 UTC, hemalathagajendran commented
Image: quay.io/hemalatha_gajendran/shallowcopy_delracecondition:latest

2024-03-13 06:29 UTC, saurabhwani5 submitted a review, later dismissed
[issue](https://github.com/IBM/ibm-spectrum-scale-csi/issues/1105) is not getting recreated using this pr

2024-03-14 01:17 UTC, Jainbrt submitted a review, later dismissed

2024-03-14 09:27 UTC, deeghuge requested changes

2024-03-14 09:27 UTC, deeghuge commented on driver/csiplugin/controllerserver.go
> +				klog.Infof("[%s] snapshot path [%s] is already deleted", loggerId, ShallowCopyRefPath)
return success from here itself

2024-03-14 09:53 UTC, hemalathagajendran commented on driver/csiplugin/controllerserver.go
> +				klog.Infof("[%s] snapshot path [%s] is already deleted", loggerId, ShallowCopyRefPath)
Done

2024-03-15 05:56 UTC, deeghuge approved these changes
LGTM

2024-03-15 05:57 UTC, merged