fix pod termination issue when kubelet mounted as symlink
IBM/ibm-spectrum-scale-csi pull request #1117
Opened 2024-03-14 11:24 UTC by badri-pathak

## Pull request checklist

```release-notes

```

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature Enhancement
- [ ] Test Automation 
- [ ] Code Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Community Operator listing 
- [ ] Other (please describe): 

## What is the current behavior?

-

## What is the new behavior?

-

## How risky is this change?
- [ ] Small, isolated change
- [ ] Medium, requires regression testing
- [ ] Large, requires functional and regression testing

2024-03-14 11:36 UTC, badri-pathak commented
Image: quay.io/badri_pathak/ibm-spectrum-scale-csi-driver:deletion_test5

2024-03-15 05:58 UTC, deeghuge commented on driver/csiplugin/nodeserver.go
> +	klog.V(4).Infof("[%s] unmount and delete targetPath:[%s], forceful:[%s]", loggerId, targetPath)
variable is missing for forceful

2024-03-15 06:12 UTC, badri-pathak commented
Image: quay.io/badri_pathak/ibm-spectrum-scale-csi-driver:deletion_test6

2024-03-16 02:49 UTC, badri-pathak commented on driver/csiplugin/nodeserver.go
> +	klog.V(4).Infof("[%s] unmount and delete targetPath:[%s], forceful:[%s]", loggerId, targetPath)
Have fixed the log message.

2024-03-18 06:00 UTC, deeghuge requested changes

2024-03-18 06:00 UTC, deeghuge commented on driver/csiplugin/nodeserver.go
> +			klog.V(4).Infof("[%s] inside when targetPath [%s] is not present", loggerId, targetPath)
remove the 'inside when'

2024-03-18 06:06 UTC, badri-pathak commented
quay.io/badri_pathak/ibm-spectrum-scale-csi-driver:deletion_test7

2024-03-18 07:18 UTC, deeghuge approved these changes

2024-03-18 10:15 UTC, hemalathagajendran approved these changes

2024-03-18 11:45 UTC, badri-pathak commented
regression passed: 
<img width="1478" alt="image" src="https://github.com/IBM/ibm-spectrum-scale-csi/assets/117259583/16081560-9660-45a0-885f-8ebdd8a2877f">

2024-03-21 05:34 UTC, Jainbrt approved these changes

2024-03-21 13:47 UTC, saurabhwani5 approved these changes

2024-03-22 05:28 UTC, merged