go mod packages updates in the driver
IBM/ibm-spectrum-scale-csi pull request #1159
Opened 2024-05-06 21:28 UTC by badri-pathak

## Pull request checklist

```release-notes

```

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature Enhancement
- [ ] Test Automation 
- [ ] Code Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Community Operator listing 
- [ ] Other (please describe): 

## What is the current behavior?

-

## What is the new behavior?

-

## How risky is this change?
- [ ] Small, isolated change
- [ ] Medium, requires regression testing
- [ ] Large, requires functional and regression testing

2024-05-06 21:29 UTC, badri-pathak commented
Image: quay.io/badri_pathak/ibm-spectrum-scale-csi-driver:gomodpackagetest_v1

2024-05-07 01:55 UTC, Jainbrt commented
HI @badri-pathak can you please do the same for operator too in the same PR ?

2024-05-08 10:03 UTC, badri-pathak commented
Images:
quay.io/badri_pathak/ibm-spectrum-scale-csi-operator:gomodpackagetest_v4
quay.io/badri_pathak/ibm-spectrum-scale-csi-driver:gomodpackagetest_v4

2024-05-09 10:09 UTC, hemalathagajendran commented
@badri-pathak Please fix the travis build errors

2024-05-09 12:44 UTC, badri-pathak commented
Images:
quay.io/badri_pathak/ibm-spectrum-scale-csi-operator:gomodpackagetest_v4
quay.io/badri_pathak/ibm-spectrum-scale-csi-driver:gomodpackagetest_v5

2024-05-09 12:53 UTC, hemalathagajendran requested changes

2024-05-09 13:28 UTC, badri-pathak commented on driver/go.mod
> +go 1.22.0
updated the version

2024-05-10 07:43 UTC, hemalathagajendran approved these changes

2024-05-14 06:35 UTC, deeghuge approved these changes

2024-05-14 06:49 UTC, merged