Fixes for defects #579 and #583
IBM/ibm-spectrum-scale-csi pull request #584
Opened 2022-01-24 12:14 UTC by madhuthorat

## Pull request checklist

```release-notes

```

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature Enhancement
- [ ] Test Automation 
- [ ] Code Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Community Operator listing 
- [ ] Other (please describe): 

## What is the current behavior?
Below defects:
1. Lost access to fileset and data if fileset is present with same name as namespace #579
2. PVC creation should fail saying storageclass parameter "type=advanced" and "filesetType: independent" can not be mutual (Issue #583)

## What is the new behavior?
Fixed for above mentioned defects

## How risky is this change?
- [x] Small, isolated change
- [ ] Medium, requires regression testing
- [ ] Large, requires functional and regression testing

2022-01-24 13:20 UTC, deeghuge submitted a review, later dismissed

2022-01-24 13:27 UTC, Jainbrt requested changes
This also can be seen with 'filesetType': 'dependent' , "inodeLimit": "1024", 'volDirBasePath': 'LW'

2022-01-25 03:26 UTC, madhuthorat commented
> volDirBasePath

Done

2022-01-25 03:35 UTC, Jainbrt approved these changes

2022-01-25 05:44 UTC, merged