Move to version 2.5.1
IBM/ibm-spectrum-scale-csi pull request #696
Opened 2022-04-11 14:19 UTC by madhuthorat

Signed-off-by: Madhu Thorat <madhu.punjabi@in.ibm.com>

## Pull request checklist
Changes to move to 2.5.1

```

## Pull request type
Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature Enhancement
- [ ] Test Automation 
- [ ] Code Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Community Operator listing 
- [ ] Other (please describe): 

## What is the current behavior?
NA

## What is the new behavior?
NA

## How risky is this change?
- [x] Small, isolated change
- [ ] Medium, requires regression testing
- [ ] Large, requires functional and regression testing

2022-04-11 14:35 UTC, Jainbrt requested changes

2022-04-11 14:35 UTC, Jainbrt commented on operator/controllers/config/constants.go
> +	LivenessProbeImage          = "us.gcr.io/k8s-artifacts-prod/sig-storage/livenessprobe:v2.5.1"
I think livenessprobe versions is 2.6.0 only for CSI 2.5.1. too

2022-04-11 14:50 UTC, madhuthorat commented on cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperator/resources.yaml
> +      tag: v2.5.1
done

2022-04-11 14:52 UTC, Jainbrt requested changes

2022-04-11 14:52 UTC, Jainbrt commented on cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperator/resources.yaml
> +        tag: v2.5.1-amd64
I think livenessprobe versions is 2.6.0 only for CSI 2.5.1. too

2022-04-11 14:52 UTC, Jainbrt commented on cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperator/resources.yaml
> +        tag: v2.5.1-ppc64le
I think livenessprobe versions is 2.6.0 only for CSI 2.5.1. too

2022-04-11 14:52 UTC, Jainbrt commented on cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperator/resources.yaml
> +        tag: v2.5.1-s390x
I think livenessprobe versions is 2.6.0 only for CSI 2.5.1. too

2022-04-12 04:55 UTC, Jainbrt requested changes

2022-04-12 08:27 UTC, Jainbrt submitted a review, later dismissed

2022-04-12 08:58 UTC, Jainbrt approved these changes

2022-04-12 09:07 UTC, merged