GUI HA Support
IBM/ibm-spectrum-scale-csi pull request #754
Opened 2022-07-04 09:06 UTC by amdabhad

- Added support for GUI HA with Active-Passive mode

Signed-off-by: amdabhad <amdabhad@in.ibm.com>

## Pull request type
Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature Enhancement
- [ ] Test Automation 
- [ ] Code Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Community Operator listing 
- [ ] Other (please describe): 

## What is the current behavior?
Only single GUI is supported.

## What is the new behavior?
Multiple GUIs are supported through Active-Passive mode.
-

## How risky is this change?
- [ ] Small, isolated change
- [x] Medium, requires regression testing
- [ ] Large, requires functional and regression testing

2022-07-16 13:32 UTC, Jainbrt requested changes
have we considered multiple configmap for ssl certificate for multiple gui endpoints?

2022-07-18 08:29 UTC, amdabhad commented
> have we considered multiple configmap for ssl certificate for multiple gui endpoints?

With current CR, SSL communication can be either enabled or disabled for all GUIs in a cluster. To enable SSL we have two options 1. Make changes in CR or 2. Have a common certificate for all GUIs (I think this is better and we need to explore on this). But this is a low priority at this point.

2022-09-01 06:33 UTC, Jainbrt approved these changes

2022-09-01 07:55 UTC, Jainbrt approved these changes

2022-09-01 07:57 UTC, merged