adding feature to control updateStrategy of daemon pods
IBM/ibm-spectrum-scale-csi pull request #908
Opened 2023-02-17 22:49 UTC by badri-pathak

## Pull request checklist

```release-notes

```

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature Enhancement
- [ ] Test Automation 
- [ ] Code Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Community Operator listing 
- [ ] Other (please describe): 

## What is the current behavior?

-

## What is the new behavior?

-

## How risky is this change?
- [ ] Small, isolated change
- [ ] Medium, requires regression testing
- [ ] Large, requires functional and regression testing

2023-02-17 22:57 UTC, badri-pathak commented
For validating the changes, this image tag can be used: quay.io/badri_pathak/operator_repo:operator_v8

2023-02-20 06:14 UTC, deeghuge requested changes
Change the variable name to DRIVER_UPGRADE_MaxUnavailable

2023-02-22 12:19 UTC, ghanshyam-11 approved these changes

2023-02-23 05:05 UTC, amdabhad commented on operator/controllers/csiscaleoperator_controller.go
> +		logger.Error(errpkg.New("daemonset maxunavailable is not valid"), "input value of daemonset maxunavailable is : "+daemonSetMaxUnavailable)
fmt.Errorf is sufficient here instead of importing an errors package for this

2023-02-23 05:07 UTC, amdabhad commented on operator/controllers/csiscaleoperator_controller.go
> +		message := "Failed to validate value of DRIVER_UPGRADE_MaxUnavailable for daemonset upgrade strategy from configmap ibm-spectrum-scale-csi-config. Please use a valid percentage value " + daemonSetM
`Please use a valid percentage value <wrong input>` doesn't look good, remove the <wrong input> from the end as it is already present in error

2023-02-23 05:15 UTC, amdabhad commented on operator/controllers/syncer/csi_node.go
> +	var strategyType appsv1.DaemonSetUpdateStrategyType = "RollingUpdate"
While doing above changes please also create a constant for "RollingUpdate" in constants.go and use it here

2023-02-23 06:44 UTC, ghanshyam-11 approved these changes

2023-02-23 07:37 UTC, amdabhad approved these changes

2023-02-23 08:51 UTC, amdabhad approved these changes

2023-02-23 09:28 UTC, deeghuge approved these changes

2023-02-23 10:02 UTC, ghanshyam-11 approved these changes

2023-02-24 03:04 UTC, merged