Fix to check gpfs type
IBM/ibm-spectrum-scale-csi pull request #946
Opened 2023-03-07 09:33 UTC by hemalathagajendran

## Pull request checklist

No

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ x] Bugfix
- [ ] Feature Enhancement
- [ ] Test Automation 
- [ ] Code Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Community Operator listing 
- [ ] Other (please describe): 

## What is the current behavior?

- stat command was used to check gpfs type

## What is the new behavior?

- /proc/mount is used to check gpfs type

## How risky is this change?
- [ ] Small, isolated change
- [ x] Medium, requires regression testing
- [ ] Large, requires functional and regression testing

2023-03-07 11:40 UTC, hemalathagajendran commented on driver/csiplugin/nodeserver.go
> +		if strings.Contains(path, gpfsPath) {
Done

2023-03-09 11:11 UTC, amdabhad approved these changes

2023-03-10 07:34 UTC, amdabhad requested changes
More changes are needed for CNSA setup

2023-07-07 12:11 UTC, amdabhad commented
Closing as there is another PR https://github.com/IBM/ibm-spectrum-scale-csi/pull/994 raised for this.

2023-07-07 12:11 UTC, closed without merging