functionality for optional variables validations
IBM/ibm-spectrum-scale-csi pull request #947
Opened 2023-03-09 06:07 UTC by badri-pathak

## Pull request checklist

```release-notes

```

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature Enhancement
- [ ] Test Automation 
- [ ] Code Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Community Operator listing 
- [ ] Other (please describe): 

## What is the current behavior?

-

## What is the new behavior?

-

## How risky is this change?
- [ ] Small, isolated change
- [ ] Medium, requires regression testing
- [ ] Large, requires functional and regression testing

2023-05-24 07:20 UTC, badri-pathak commented
Images:
quay.io/badri_pathak/ibm-spectrum-scale-csi-operator:variable_validation_v2
quay.io/badri_pathak/ibm-spectrum-scale-csi-driver:variable_validation_v2

2023-05-25 11:12 UTC, amdabhad commented on operator/controllers/csiscaleoperator_controller.go
> +	if len(invalidEnv) > 0 || len(invalidEnvValue) > 0 {
invalidEnvValue condition is not needed

2023-05-25 11:12 UTC, amdabhad commented on operator/controllers/csiscaleoperator_controller.go
> +		SetStatusAndRaiseEvent(instance, r.Recorder, corev1.EventTypeWarning, string(config.StatusConditionSuccess),
SetStatusAndRaiseEvent is not needed for this info message

2023-05-25 11:12 UTC, amdabhad commented on operator/controllers/csiscaleoperator_controller.go
> +			logger.Error(fmt.Errorf("%s  : daemonset maxunavailable is not valid", daemonSetMaxUnavailable), "input value of daemonset maxunavailable is : ")
This logger.Error statement doesn't seem right, earlier one was fine.

2023-05-25 13:08 UTC, amdabhad commented on operator/controllers/csiscaleoperator_controller.go
> +		invalidEnvValue[key] = value
Discussed with Badri and even though the defaults are set, keeping invalidEnvValue to print wrong input values for the valid keys.

2023-05-25 13:17 UTC, amdabhad commented on operator/controllers/csiscaleoperator_controller.go
> +		cmData, daemonSetMaxUnavailable = r.parseConfigMap(instance, cm)
We shouldn't validate the configmap data every time in the reconcile loop, validation should be done only when there is a change in the configmap data.

2023-05-26 06:41 UTC, badri-pathak commented
Images:
quay.io/badri_pathak/ibm-spectrum-scale-csi-operator:variable_validation_v5
quay.io/badri_pathak/ibm-spectrum-scale-csi-driver:variable_validation_v5

2023-05-26 08:18 UTC, amdabhad approved these changes

2023-05-26 14:26 UTC, saurabhwani5 commented
Adding issues Here :
1. Log level is not working as per functionality , even if I'm setting it to FATAL I can see all the logs :
```
[root@saurabh9-master functional-tests]# oc logs ibm-spectrum-scale-csi-c78zg
I0526 14:20:03.131807       1 main.go:68] [LOGLEVEL] found in the env : FATAL
I0526 14:20:03.131914       1 main.go:71] [PERSISTENT_LOG] found in the env : DISABLED
I0526 14:20:03.131921       1 main.go:74] [NODEPUBLISH_METHOD] found in the env : BINDMOUNT
I0526 14:20:03.131964       1 main.go:109] [181ab5fe-5c45-4ec5-8a9c-865ccaa2645a] Version Info: commit ()
I0526 14:20:03.132010       1 gpfs.go:122] [181ab5fe-5c45-4ec5-8a9c-865ccaa2645a] gpfs GetScaleDriver
I0526 14:20:03.132018       1 gpfs.go:198] [181ab5fe-5c45-4ec5-8a9c-865ccaa2645a] gpfs SetupScaleDriver. name: spectrumscale.csi.ibm.com, version: 2.10.0, nodeID: saurabh9-worker-1.fyre.ibm.com
I0526 14:20:03.132040       1 gpfs.go:245] [181ab5fe-5c45-4ec5-8a9c-865ccaa2645a] gpfs PluginInitialize
I0526 14:20:03.132343       1 connectors.go:121] [181ab5fe-5c45-4ec5-8a9c-865ccaa2645a] connector GetSpectrumScaleConnector
I0526 14:20:03.172018       1 gpfs.go:282] [181ab5fe-5c45-4ec5-8a9c-865ccaa2645a] IBM Storage Scale: Plugin initialized
I0526 14:20:03.172047       1 gpfs.go:152] [181ab5fe-5c45-4ec5-8a9c-865ccaa2645a] gpfs AddVolumeCapabilityAccessModes
I0526 14:20:03.172055       1 gpfs.go:163] [181ab5fe-5c45-4ec5-8a9c-865ccaa2645a] gpfs AddControllerServiceCapabilities
I0526 14:20:03.172068       1 gpfs.go:231] [181ab5fe-5c45-4ec5-8a9c-865ccaa2645a] volume stats capabililty is enabled
I0526 14:20:03.172073       1 gpfs.go:174] [181ab5fe-5c45-4ec5-8a9c-865ccaa2645a] gpfs AddNodeServiceCapabilities
I0526 14:20:03.172080       1 gpfs.go:127] [181ab5fe-5c45-4ec5-8a9c-865ccaa2645a] gpfs NewIdentityServer
I0526 14:20:03.172085       1 gpfs.go:145] [181ab5fe-5c45-4ec5-8a9c-865ccaa2645a] gpfs NewNodeServer
I0526 14:20:03.172089       1 gpfs.go:134] [181ab5fe-5c45-4ec5-8a9c-865ccaa2645a] gpfs NewControllerServer
I0526 14:20:03.172095       1 gpfs.go:287] [181ab5fe-5c45-4ec5-8a9c-865ccaa2645a] Driver: spectrumscale.csi.ibm.com version: 2.10.0
I0526 14:20:03.172197       1 server.go:96] Start listening with scheme unix, addr /var/lib/kubelet/plugins/spectrumscale.csi.ibm.com/csi.sock
I0526 14:20:03.172591       1 server.go:118] Listening for connections on address: &net.UnixAddr{Name:"/var/lib/kubelet/plugins/spectrumscale.csi.ibm.com/csi.sock", Net:"unix"}
I0526 14:20:03.845696       1 utils.go:54] [2f4bd808-f366-4113-9daf-1a442dcebe98] GRPC call: /csi.v1.Identity/GetPluginInfo
I0526 14:20:03.845734       1 identityserver.go:79] [2f4bd808-f366-4113-9daf-1a442dcebe98] Using default GetPluginInfo
I0526 14:20:03.845742       1 utils.go:61] [2f4bd808-f366-4113-9daf-1a442dcebe98] GRPC response: name:"spectrumscale.csi.ibm.com" vendor_version:"2.10.0"
I0526 14:20:03.845867       1 utils.go:65] [2f4bd808-f366-4113-9daf-1a442dcebe98] Time taken to execute GRPC request(in milli): 0
I0526 14:20:04.536980       1 utils.go:54] [f4346120-5f20-4ce3-aef0-8825cd705e36] GRPC call: /csi.v1.Identity/GetPluginInfo
I0526 14:20:04.537007       1 identityserver.go:79] [f4346120-5f20-4ce3-aef0-8825cd705e36] Using default GetPluginInfo
I0526 14:20:04.537016       1 utils.go:61] [f4346120-5f20-4ce3-aef0-8825cd705e36] GRPC response: name:"spectrumscale.csi.ibm.com" vendor_version:"2.10.0"
I0526 14:20:04.537090       1 utils.go:65] [f4346120-5f20-4ce3-aef0-8825cd705e36] Time taken to execute GRPC request(in milli): 0
I0526 14:20:04.794418       1 utils.go:54] [74dc001e-1039-4df0-8c45-96cda1f3909b] GRPC call: /csi.v1.Node/NodeGetInfo
I0526 14:20:04.794460       1 utils.go:61] [74dc001e-1039-4df0-8c45-96cda1f3909b] GRPC response: node_id:"saurabh9-worker-1.fyre.ibm.com"
I0526 14:20:04.794633       1 utils.go:65] [74dc001e-1039-4df0-8c45-96cda1f3909b] Time taken to execute GRPC request(in milli): 0
I0526 14:20:55.343221       1 utils.go:54] [dca3f9c0-a955-4f3b-b776-ef5e590849d9] GRPC call: /csi.v1.Identity/Probe
E0526 14:20:55.371598       1 identityserver.go:62] [dca3f9c0-a955-4f3b-b776-ef5e590849d9] Probe: GPFS component on node saurabh9-worker-1.fyre.ibm.com is not healthy. Error: <nil>
I0526 14:20:55.371628       1 utils.go:61] [dca3f9c0-a955-4f3b-b776-ef5e590849d9] GRPC response: ready:<value:true >
I0526 14:20:55.371829       1 utils.go:65] [dca3f9c0-a955-4f3b-b776-ef5e590849d9] Time taken to execute GRPC request(in milli): 28
I0526 14:20:55.415672       1 utils.go:54] [6236d6ae-1cf5-43ec-91b9-c7814703b2d6] GRPC call: /csi.v1.Identity/GetPluginInfo
I0526 14:20:55.415715       1 identityserver.go:79] [6236d6ae-1cf5-43ec-91b9-c7814703b2d6] Using default GetPluginInfo
I0526 14:20:55.415724       1 utils.go:61] [6236d6ae-1cf5-43ec-91b9-c7814703b2d6] GRPC response: name:"spectrumscale.csi.ibm.com" vendor_version:"2.10.0"
I0526 14:20:55.415837       1 utils.go:65] [6236d6ae-1cf5-43ec-91b9-c7814703b2d6] Time taken to execute GRPC request(in milli): 0
I0526 14:20:55.416770       1 utils.go:54] [c45caf16-3fcd-48a7-bc61-ece8a36e1cee] GRPC call: /csi.v1.Identity/GetPluginCapabilities
I0526 14:20:55.416807       1 utils.go:61] [c45caf16-3fcd-48a7-bc61-ece8a36e1cee] GRPC response: capabilities:<service:<type:CONTROLLER_SERVICE > >
I0526 14:20:55.417166       1 utils.go:65] [c45caf16-3fcd-48a7-bc61-ece8a36e1cee] Time taken to execute GRPC request(in milli): 1
I0526 14:20:55.418011       1 utils.go:54] [f33d5317-d853-4c1b-84a5-da4f898c5eec] GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I0526 14:20:55.418046       1 controllerserver.go:1686] [f33d5317-d853-4c1b-84a5-da4f898c5eec] ControllerGetCapabilities called with req: &csi.ControllerGetCapabilitiesRequest{XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
I0526 14:20:55.418097       1 utils.go:61] [f33d5317-d853-4c1b-84a5-da4f898c5eec] GRPC response: capabilities:<rpc:<type:CREATE_DELETE_VOLUME > > capabilities:<rpc:<type:PUBLISH_UNPUBLISH_VOLUME > > capabilities:<rpc:<type:CREATE_DELETE_SNAPSHOT > > capabilities:<rpc:<type:EXPAND_VOLUME > > capabilities:<rpc:<type:CLONE_VOLUME > >
I0526 14:20:55.418377       1 utils.go:65] [f33d5317-d853-4c1b-84a5-da4f898c5eec] Time taken to execute GRPC request(in milli): 0
I0526 14:22:02.724890       1 utils.go:54] [e0f69a4f-dc8b-4320-85c4-3feab7884955] GRPC call: /csi.v1.Identity/Probe
E0526 14:22:02.755960       1 identityserver.go:62] [e0f69a4f-dc8b-4320-85c4-3feab7884955] Probe: GPFS component on node saurabh9-worker-1.fyre.ibm.com is not healthy. Error: <nil>
I0526 14:22:02.756014       1 utils.go:61] [e0f69a4f-dc8b-4320-85c4-3feab7884955] GRPC response: ready:<value:true >
I0526 14:22:02.756104       1 utils.go:65] [e0f69a4f-dc8b-4320-85c4-3feab7884955] Time taken to execute GRPC request(in milli): 32
I0526 14:23:17.397789       1 utils.go:54] [d7120185-bf97-4854-aba6-3292a899fdd3] GRPC call: /csi.v1.Controller/DeleteVolume
I0526 14:23:17.397867       1 controllerserver.go:1565] [d7120185-bf97-4854-aba6-3292a899fdd3] DeleteVolume [volume_id:"0;0;11840458782091175455;9F730B0A:6432E6FC;;;/ibm/fs1/spectrum-scale-csi-volume-store/.volumes/pvc-bcb68ae6-a34a-4dbe-ae9b-5c1edb5a2aba" ]
I0526 14:23:17.398020       1 gpfs.go:185] [d7120185-bf97-4854-aba6-3292a899fdd3] gpfs ValidateControllerServiceRequest
I0526 14:23:17.399552       1 utils.go:54] [33248b72-7395-42dd-8082-15db32226322] GRPC call: /csi.v1.Controller/CreateVolume
I0526 14:23:17.399630       1 controllerserver.go:574] [33248b72-7395-42dd-8082-15db32226322] create volume req: name:"pvc-8599f187-6711-4a1e-9c65-a17877e90373" capacity_range:<required_bytes:1073741824 > volume_capabilities:<mount:<fs_type:"gpfs" > access_mode:<mode:MULTI_NODE_MULTI_WRITER > > parameters:<key:"clusterId" value:"11840458782091175455" > parameters:<key:"csi.storage.k8s.io/pv/name" value:"pvc-8599f187-6711-4a1e-9c65-a17877e90373" > parameters:<key:"csi.storage.k8s.io/pvc/name" value:"pvc-elegant-fox-893" > parameters:<key:"csi.storage.k8s.io/pvc/namespace" value:"ibm-spe [...]

2023-05-26 16:24 UTC, badri-pathak commented
@hemalathagajendran can we check this issue together?

2023-05-29 09:54 UTC, Jainbrt requested changes
have we not considered VAR_DRIVER_VOLUME_STATS_CAPABILITY variable for valid values ?

2023-05-29 10:37 UTC, badri-pathak commented
> have we not considered VAR_DRIVER_VOLUME_STATS_CAPABILITY variable for valid values ?

Added VAR_DRIVER_VOLUME_STATS_CAPABILITY in the latest commit. Default will be enabled. Please valid once.

2023-05-29 10:38 UTC, badri-pathak commented
Latest images: 
quay.io/badri_pathak/ibm-spectrum-scale-csi-driver:variable_validation_v10
quay.io/badri_pathak/ibm-spectrum-scale-csi-operator:variable_validation_v10

2023-05-30 12:19 UTC, saurabhwani5 requested changes
`DRIVER_UPGRADE_MAXUNAVAILABLE` is not setting the value

2023-06-05 14:34 UTC, amdabhad commented
@Jainbrt, @saurabhwani5, events will be added in another PR and logger issue present in dev will be fixed under https://github.com/IBM/ibm-spectrum-scale-csi/issues/979, please approve the PR if there is nothing else expected.

2023-06-05 15:17 UTC, Jainbrt submitted a review, later dismissed

2023-06-07 14:32 UTC, saurabhwani5 commented
I have  following Images for final review, Thanks @badri-pathak for all the required changes:
```
quay.io/badri_pathak/ibm-spectrum-scale-csi-operator:variable_validation_v23
quay.io/badri_pathak/ibm-spectrum-scale-csi-driver:variable_validation_v16
```

2023-06-07 14:32 UTC, saurabhwani5 approved these changes

2023-06-07 14:41 UTC, Jainbrt submitted a review, later dismissed

2023-06-08 05:36 UTC, amdabhad commented on operator/controllers/syncer/csi_node.go
> +	logger.Info("upgrade_straegty shouldn't be present in cmEnvVars", "cmEnvVars:", cmEnvVars)
This log statement seems unnecessary as cmEnvVars will never have upgrade strategy due to condition at line no 105.

2023-06-08 06:00 UTC, amdabhad approved these changes

2023-06-08 07:03 UTC, merged