Fix for logger issue
IBM/ibm-spectrum-scale-csi pull request #987
Opened 2023-06-12 17:52 UTC by hemalathagajendran

## Pull request checklist

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ x] Bugfix
- [ ] Feature Enhancement
- [ ] Test Automation 
- [ ] Code Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Community Operator listing 
- [ ] Other (please describe): 

## What is the current behavior?

- klog tries to log into /tmp directory by default which is restricted now by enabling "readOnlyRootFileSystem" to true. To avoid this error "logtosderr" is set to true which cause log level issues

## What is the new behavior?

- After making necessary "readOnlyRootFileSystem" to false for driver container pod log level issues are resolved.

## How risky is this change?
- [ x] Small, isolated change
- [ ] Medium, requires regression testing
- [ ] Large, requires functional and regression testing

2023-06-13 09:12 UTC, amdabhad approved these changes

2023-06-13 09:24 UTC, badri-pathak approved these changes

2023-06-14 05:16 UTC, saurabhwani5 requested changes
when Warning level log level is set and persistent volume is enabled , logs are getting saved of info in log file

2023-06-14 06:15 UTC, hemalathagajendran commented
> when Warning level log level is set and persistent log is enabled , logs are getting saved of info in log file
> 
> ```
> kind: ConfigMap
> apiVersion: v1
> metadata:
>   name: ibm-spectrum-scale-csi-config
>   namespace: ibm-spectrum-scale-csi-driver
> data:
>   VAR_DRIVER_LOGLEVEL: WARNING
>   VAR_DRIVER_PERSISTENT_LOG: ENABLED
>   VAR_DRIVER_VOLUME_STATS_CAPABILITY: DISABLED
>   VAR_DRIVER_NODEPUBLISH_METHOD: SYMLINK
>   DRIVER_UPGRADE_MAXUNAVAILABLE:  90%
> ```

Log Level doesn't affect any logs saved in file. Log levels will have impact only on driver pod logs. This is already existing functionality only.

2023-06-14 07:04 UTC, saurabhwani5 approved these changes

2023-06-14 07:06 UTC, merged